name: Reusable Workflow
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      test-type:
        required: true
        type: string
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Install STUMPY And Other Dependencies
        run: python -m pip install --editable .[ci]
        shell: bash
      - name: Run Black
        run: black --check --diff ./
        shell: bash
      - name: Run Flake8
        run: flake8 ./
        shell: bash
      - name: Link OpenMP
        run: |
             if [ "$RUNNER_OS" == "macOS" ]; then
                  brew link --force libomp
             fi
        shell: bash
      - name: Show Full Numba Environment
        run: python -m numba -s
        shell: bash
      - name: Run Tests
        run: ./test.sh ${{ inputs.test-type }}
        shell: bash